USE tcc;

DELETE FROM USER_STAMP_CARD  WHERE COLLECT_STAMP_QTY = 0 AND USER_ID IN (SELECT ID FROM USER U WHERE U.USER_TYPE = 0);

DELETE FROM USER WHERE USER_TYPE = 0 ;

ALTER TABLE `MERCHANT_CONFIG` ADD COLUMN `SMS_BASE_URL`  varchar(100) NOT NULL AFTER `IQUIRY_EMAIL_TEMPLATE`, ADD COLUMN `SMS_USER_NAME`  varchar(100) NOT NULL AFTER `SMS_BASE_URL`, ADD COLUMN `SMS_PASSWORD`  varchar(100) NOT NULL AFTER `SMS_USER_NAME`;
ALTER TABLE `MERCHANT_CONFIG` ADD COLUMN `FB_APP_ID`  varchar(100) NOT NULL AFTER `SMS_PASSWORD`, ADD COLUMN `FB_APP_TOKEN`  varchar(100) NOT NULL AFTER `FB_APP_ID`, ADD COLUMN `FB_DEBUG_TOKEN_API`  varchar(100) NOT NULL AFTER `FB_APP_TOKEN`;

-- UPDATE 
UPDATE SYSTEM_FUNCTION SET IS_DELETED = 0 WHERE ID IN (39,42,43,44,45);

-- ----------------------------
-- Table structure for `SMS_VERIFY`
-- ----------------------------
DROP TABLE IF EXISTS `SMS_VERIFY`;
CREATE TABLE `SMS_VERIFY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PHONE_AREA_CODE` varchar(20) NOT NULL,
  `PHONE` varchar(20) NOT NULL,
  `MERCHANT_ID` bigint(20) NOT NULL,
  `VERIFY_CODE` varchar(10) NOT NULL,
  `EXPIRY_TIME` datetime NOT NULL,
  `STATUS` tinyint(1) NOT NULL ,
  `MESSAGE_ID` varchar(255) DEFAULT NULL,
  `VERIFY_TYPE`  tinyint(1) NOT NULL COMMENT '1: Registration, 2: Login, 3: User Change MobileNo' ,
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY(MERCHANT_ID,PHONE_AREA_CODE,PHONE,VERIFY_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- ----------------------------
-- Table structure for `SMS_LOG`
-- ----------------------------
DROP TABLE IF EXISTS `SMS_LOG`;
CREATE TABLE `SMS_LOG` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MERCHANT_ID` bigint(20) NOT NULL,
  `PHONE` varchar(20) NOT NULL,
  `TEXT` varchar(255) NOT NULL,
  `MESSAGE_ID` varchar(255) DEFAULT NULL,
  `RESULT` varchar(500) DEFAULT NULL,
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for `TEMP_EMAIL_USER`
-- ----------------------------
DROP TABLE IF EXISTS `TEMP_EMAIL_USER`;
CREATE TABLE `TEMP_EMAIL_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(100) NOT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `MERCHANT_ID` bigint(20) NOT NULL,
  `EMAIL_VALIDATION_CODE` varchar(100) NULL,
  `VALIDATION_CODE_EXPRIED_TIME` datetime DEFAULT NULL,
  `IS_EMAIL_VALIDATION` tinyint(1) NULL DEFAULT 0 COMMENT '0-false 1-true',
  `RESET_PWD_EXPRIED_TIME` datetime DEFAULT NULL,
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY(EMAIL,MERCHANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- drop coupon and coupon lang map
DROP TABLE IF EXISTS `USER_COUPON`;
DROP TABLE IF EXISTS `COUPON_LANG_MAP`;
DROP TABLE IF EXISTS `COUPON`;

-- ----------------------------
-- Table structure for COUPON
-- ----------------------------
CREATE TABLE `COUPON` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MERCHANT_ID` bigint(20) NOT NULL,
  `CAMPAIGN_ID` bigint(20) DEFAULT NULL,
  `COLLECT_START_TIME` datetime DEFAULT NULL,
  `COLLECT_END_TIME` datetime DEFAULT NULL,
  `REDEEM_START_TIME` datetime DEFAULT NULL,
  `REDEEM_END_TIME` datetime DEFAULT NULL,
  `IS_AFTER_COLLECT` tinyint(1) DEFAULT '0' COMMENT '0 - false  1 - true ',
  `END_DAYS_AFTER_COLLECT` int(5) DEFAULT NULL,
  `TOTAL_QTY` int(11) NOT NULL DEFAULT '-1' COMMENT '-1 无限制',
  `ISSUED_QTY` int(11) NOT NULL DEFAULT '0',
  `ISSUED_QUOTA_TYPE` tinyint(1) DEFAULT '0' COMMENT '0 - 没限制  1 - day  2 - month  3 - year  4 - campaign  5 - coupon period',
  `ISSUED_QUOTA_QTY` int(11) DEFAULT NULL,
  `TYPE` tinyint(1) NOT NULL COMMENT '1 - stamps  2 - point  3 - Cash  4 - Discount',
  `IS_USER_TIER` tinyint(1) DEFAULT '0' COMMENT '0 - false   1 - true',
  `USER_MEMBER_TIER_ID` bigint(20) DEFAULT NULL,
  `REWARD_QTY` double(7,3) DEFAULT NULL,
  `MAX_REWARD_QTY` double(7,3) DEFAULT NULL,
  `IS_USE_WITH_SAME_COUPON` tinyint(1) DEFAULT '0' COMMENT '0 - false   1 - true',
  `IS_USE_WITH_OTHER_COUPON` tinyint(1) DEFAULT '0' COMMENT '0 - on   1 - off',
  `IS_TRANSFERRABLE` tinyint(1) DEFAULT '0' COMMENT '0 - false 1 - true',
  `STATUS` tinyint(1) NOT NULL DEFAULT '2' COMMENT '2 - Active  4 - Inactive',
  `SORT_ORDER` int(11) NOT NULL DEFAULT '0',
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `CAMPAIGN_ID` (`CAMPAIGN_ID`),
  KEY `MERCHANT_ID` (`MERCHANT_ID`),
  FOREIGN KEY (`CAMPAIGN_ID`) REFERENCES `CAMPAIGN` (`ID`),
  FOREIGN KEY (`MERCHANT_ID`) REFERENCES `MERCHANT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for BEACON_COUPON_MAP
-- ----------------------------
DROP TABLE IF EXISTS `BEACON_COUPON_MAP`;
CREATE TABLE `BEACON_COUPON_MAP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COUPON_ID` bigint(20) NOT NULL,
  `BEACON_ID` bigint(20) DEFAULT NULL,
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `COUPON_ID` (`COUPON_ID`),
  FOREIGN KEY (`COUPON_ID`) REFERENCES `COUPON` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for COUPON_CODE_MAP
-- ----------------------------
DROP TABLE IF EXISTS `COUPON_CODE_MAP`;
CREATE TABLE `COUPON_CODE_MAP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MERCHANT_ID` bigint(20) NOT NULL,
  `COUPON_ID` bigint(20) NOT NULL DEFAULT '0',
  `EXTERNAL_COUPON_CODE` varchar(20) DEFAULT NULL,
  `COUPON_CODE` varchar(20) NOT NULL,
  `STATUS` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态:1 - Active  2 - Inactive  3 - Used',
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `MERCHANT_ID` (`MERCHANT_ID`) USING BTREE,
  KEY `COUPON_ID` (`COUPON_ID`),
  FOREIGN KEY (`MERCHANT_ID`) REFERENCES `MERCHANT` (`ID`),
  FOREIGN KEY (`COUPON_ID`) REFERENCES `COUPON` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for coupon_collect_method_map
-- ----------------------------
DROP TABLE IF EXISTS `COUPON_COLLECT_METHOD_MAP`;
CREATE TABLE `COUPON_COLLECT_METHOD_MAP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COUPON_ID` bigint(20) NOT NULL,
  `COLLECT_METHOD` tinyint(1) NOT NULL COMMENT '1 - Registration  2 - Free to collect  3 - Beacon  4 - Complete profile  5 - Purchase product  6 - Purchase amount  7 - By purchase product brand  8 - Purchase product + amount  9 - By purchase product brand + amount  10 - Referral  11 - by stamp  12 - by pionts',
  `COLLECT_METHOD_QTY` int(11) DEFAULT NULL,
  `COLLECT_METHOD_AMOUNT` double(5,2) DEFAULT NULL,
  `COLLECT_PRODUCT_CODE` varchar(20) DEFAULT NULL,
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `COUPON_ID` (`COUPON_ID`),
  FOREIGN KEY (`COUPON_ID`) REFERENCES `COUPON` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for coupon_collect_quota_map
-- ----------------------------
DROP TABLE IF EXISTS `COUPON_COLLECT_QUOTA_MAP`;
CREATE TABLE `COUPON_COLLECT_QUOTA_MAP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COUPON_ID` bigint(20) NOT NULL,
  `COLLECT_QUOTA_TYPE` tinyint(1) NOT NULL COMMENT '1 - day  2 - month  3 - year  4 - campaign  5 - coupon period  6 - once',
  `COLLECT_QUOTA_QTY` int(11) DEFAULT NULL,
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `COUPON_ID` (`COUPON_ID`),
  FOREIGN KEY (`COUPON_ID`) REFERENCES `COUPON` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for COUPON_LANG_MAP
-- ----------------------------
CREATE TABLE `COUPON_LANG_MAP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COUPON_ID` bigint(20) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `TERMS` varchar(500) DEFAULT NULL,
  `IMG` varchar(100) DEFAULT NULL,
  `DESCR` varchar(3000) DEFAULT NULL,
  `LANG_CODE` varchar(20) NOT NULL,
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT '0' DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `COUPON_ID` (`COUPON_ID`),
  FOREIGN KEY (`COUPON_ID`) REFERENCES `COUPON` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for coupon_redeem_method_map
-- ----------------------------
DROP TABLE IF EXISTS `COUPON_REDEEM_METHOD_MAP`;
CREATE TABLE `COUPON_REDEEM_METHOD_MAP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COUPON_ID` bigint(20) NOT NULL,
  `REDEEM_METHOD` tinyint(1) NOT NULL COMMENT '0 - 没限制  1 - By purchase product  2 - By purchase amount  3 - By purchase product brand  4 - By purchase product + amount  5 - By purchase product brand + amount',
  `REDEEM_METHOD_QTY` double(5,2) DEFAULT NULL,
  `REDEEM_METHOD_AMOUNT` double(5,2) DEFAULT NULL,
  `REDEEM_PRODUCT_CODE` varchar(20) DEFAULT NULL,
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `COUPON_ID` (`COUPON_ID`),
  FOREIGN KEY (`COUPON_ID`) REFERENCES `COUPON` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for coupon_redeem_quota_map
-- ----------------------------
DROP TABLE IF EXISTS `COUPON_REDEEM_QUOTA_MAP`;
CREATE TABLE `COUPON_REDEEM_QUOTA_MAP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COUPON_ID` bigint(20) NOT NULL,
  `REDEEM_QUOTA_TYPE` tinyint(1) DEFAULT NULL,
  `REDEEM_QUOTA_QTY` int(11) DEFAULT NULL,
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `COUPON_ID` (`COUPON_ID`),
  FOREIGN KEY (`COUPON_ID`) REFERENCES `COUPON` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for USER_COUPON
-- ----------------------------
CREATE TABLE `USER_COUPON` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT,
    `MERCHANT_ID` bigint(20) NOT NULL,
	`USER_ID` bigint(20) NOT NULL,
	`COUPON_ID` bigint(20) NOT NULL,
	`STATUS` tinyint(1) NOT NULL COMMENT '1- Active 2- Redeemed',
	`QR_CODE` varchar(100)NOT NULL,
	`REDEEMED_DATE` datetime DEFAULT NULL,
    
    `CREATED_BY` varchar(100) DEFAULT NULL,
    `CREATED_TIME` datetime DEFAULT NULL,
    `UPDATED_BY` varchar(100) DEFAULT NULL,
    `UPDATED_TIME` datetime DEFAULT NULL,
    `IS_DELETED` tinyint(1) DEFAULT '0',
    PRIMARY KEY (`ID`),
    FOREIGN KEY(USER_ID) REFERENCES USER(ID),
    FOREIGN KEY(MERCHANT_ID) REFERENCES MERCHANT(ID),
    FOREIGN KEY(COUPON_ID) REFERENCES COUPON(ID),
    UNIQUE KEY(QR_CODE,MERCHANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE CAMPAIGN_GIFT_EXCHANGE_TYPE MODIFY COLUMN STAMP_QTY bigint(15);
ALTER TABLE USER_STAMP_CARD MODIFY COLUMN COLLECT_STAMP_QTY bigint(15);
ALTER TABLE USER_STAMP_HISTORY MODIFY COLUMN STAMP_QTY bigint(15);
ALTER TABLE USER_RESERVATION MODIFY COLUMN STAMP_QTY bigint(15);

ALTER TABLE POS_TRANS_STAMP MODIFY COLUMN ITEM_CODE_QTY text;
ALTER TABLE POS_REDEEM_GIFT MODIFY COLUMN ITEM_CODE_QTY text;
ALTER TABLE POS_RESERVATION_PICK_UP MODIFY COLUMN ITEM_CODE_QTY text;

ALTER TABLE USER DROP COLUMN EMAIL_VALIDATION_CODE;
ALTER TABLE USER DROP COLUMN VALIDATION_CODE_EXPRIED_TIME;
ALTER TABLE USER DROP COLUMN RESET_PWD_EXPRIED_TIME;
ALTER TABLE USER DROP COLUMN PHONE_VALIDATION_CODE;

ALTER TABLE `USER_COUPON` ADD COLUMN `REMARK`  varchar(500) NULL AFTER `REDEEMED_DATE`;
ALTER TABLE `USER_STAMP_HISTORY` ADD COLUMN `TRANS_AMT`  decimal(15,2) NULL AFTER `TRANS_NO`, ADD COLUMN `RELATED_USER_COUPON`  varchar(100) NULL AFTER `REMARKS`;

-- insert system function
INSERT INTO `SYSTEM_FUNCTION` (`ID`, `FUNC_CODE`, `FUNC_NAME`, `FUNC_TYPE`, `FUNC_DESC`, `IS_FOLDER`, `PARENT_ID`, `PAGE_INFO`, `DISPLAY_ORDER`, `ICON`, `WEB_INFO`, `CREATED_BY`, `CREATED_TIME`, `UPDATED_BY`, `UPDATED_TIME`, `IS_DELETED`) VALUES ('119', 'CUSTOMER_COUPON', 'Customer coupon', '3', 'Customer coupon', '0', '87', '', '120', '', '', 'admin', '2017-12-08 17:23:00', '', NULL, '0');
INSERT INTO `SYSTEM_FUNCTION` (`ID`, `FUNC_CODE`, `FUNC_NAME`, `FUNC_TYPE`, `FUNC_DESC`, `IS_FOLDER`, `PARENT_ID`, `PAGE_INFO`, `DISPLAY_ORDER`, `ICON`, `WEB_INFO`, `CREATED_BY`, `CREATED_TIME`, `UPDATED_BY`, `UPDATED_TIME`, `IS_DELETED`) VALUES ('120', 'CUSTOMER_COUPON_VIEW', 'Customer coupon view', '2', 'Customer coupon view', '0', '119', '/getUserCouponList', '121', '', '', 'admin', '2017-12-08 17:23:00', '', NULL, '0');
INSERT INTO `SYSTEM_FUNCTION` (`ID`, `FUNC_CODE`, `FUNC_NAME`, `FUNC_TYPE`, `FUNC_DESC`, `IS_FOLDER`, `PARENT_ID`, `PAGE_INFO`, `DISPLAY_ORDER`, `ICON`, `WEB_INFO`, `CREATED_BY`, `CREATED_TIME`, `UPDATED_BY`, `UPDATED_TIME`, `IS_DELETED`) VALUES ('121', 'CUSTOMER_COUPON_UPDATE', 'Customer coupon update', '2', 'Customer coupon update', '0', '119', '/getUserCouponList,/revokeUserCoupon,/addUserCoupon', '122', '', '', 'admin', '2017-12-08 17:23:00', '', NULL, '0');
INSERT INTO `SYSTEM_FUNCTION_FILTER` (`ID`, `FILTER_CODE`, `FUNC_ID`, `FILTER_NAME`, `FILTER_DESC`, `CREATED_BY`, `CREATED_TIME`, `UPDATED_BY`, `UPDATED_TIME`, `IS_DELETED`) VALUES ('6', '1', '119', 'coupon management', 'coupon management', 'admin', '2017-12-08 17:36:06', NULL, NULL, '0');
INSERT INTO `SYSTEM_FUNCTION_FILTER` (`ID`, `FILTER_CODE`, `FUNC_ID`, `FILTER_NAME`, `FILTER_DESC`, `CREATED_BY`, `CREATED_TIME`, `UPDATED_BY`, `UPDATED_TIME`, `IS_DELETED`) VALUES ('7', '1', '120', 'coupon management', 'coupon management', 'admin', '2017-12-08 17:34:50', NULL, NULL, '0');
INSERT INTO `SYSTEM_FUNCTION_FILTER` (`ID`, `FILTER_CODE`, `FUNC_ID`, `FILTER_NAME`, `FILTER_DESC`, `CREATED_BY`, `CREATED_TIME`, `UPDATED_BY`, `UPDATED_TIME`, `IS_DELETED`) VALUES ('8', '1', '121', 'coupon management', 'coupon management', 'admin', '2017-12-08 17:35:20', NULL, NULL, '0');

INSERT INTO `SYSTEM_FUNCTION_FILTER` (`ID`, `FILTER_CODE`, `FUNC_ID`, `FILTER_NAME`, `FILTER_DESC`, `CREATED_BY`, `CREATED_TIME`, `UPDATED_BY`, `UPDATED_TIME`, `IS_DELETED`) VALUES ('9', '1', '73', 'coupon management', 'coupon management', 'admin', '2017-12-12 14:58:15', NULL, NULL, '0');
INSERT INTO `SYSTEM_FUNCTION_FILTER` (`ID`, `FILTER_CODE`, `FUNC_ID`, `FILTER_NAME`, `FILTER_DESC`, `CREATED_BY`, `CREATED_TIME`, `UPDATED_BY`, `UPDATED_TIME`, `IS_DELETED`) VALUES ('10', '1', '74', 'coupon management', 'coupon management', 'admin', '2017-12-12 14:58:30', NULL, NULL, '0');
INSERT INTO `SYSTEM_FUNCTION_FILTER` (`ID`, `FILTER_CODE`, `FUNC_ID`, `FILTER_NAME`, `FILTER_DESC`, `CREATED_BY`, `CREATED_TIME`, `UPDATED_BY`, `UPDATED_TIME`, `IS_DELETED`) VALUES ('11', '1', '82', 'coupon management', 'coupon management', 'admin', '2017-12-12 14:58:52', NULL, NULL, '0');
INSERT INTO `SYSTEM_FUNCTION_FILTER` (`ID`, `FILTER_CODE`, `FUNC_ID`, `FILTER_NAME`, `FILTER_DESC`, `CREATED_BY`, `CREATED_TIME`, `UPDATED_BY`, `UPDATED_TIME`, `IS_DELETED`) VALUES ('12', '1', '83', 'coupon management', 'coupon management', 'admin', '2017-12-12 14:59:06', NULL, NULL, '0');
UPDATE `SYSTEM_FUNCTION` SET `ID`='73', `FUNC_CODE`='COLLECT_COUPON_REPORT', `FUNC_NAME`='Collect Coupon report', `FUNC_TYPE`='1', `FUNC_DESC`='Collect Coupon report', `IS_FOLDER`='1', `PARENT_ID`='67', `PAGE_INFO`='', `DISPLAY_ORDER`='107', `ICON`='', `WEB_INFO`='main.collectCouponReport', `CREATED_BY`='admin', `CREATED_TIME`='2017-08-15 19:15:00', `UPDATED_BY`='', `UPDATED_TIME`=NULL, `IS_DELETED`='0' WHERE (`ID`='73');
UPDATE `SYSTEM_FUNCTION` SET `ID`='74', `FUNC_CODE`='REDEEM_COUPON_REPORT', `FUNC_NAME`='Redeem Coupon report', `FUNC_TYPE`='1', `FUNC_DESC`='Redeem Coupon report', `IS_FOLDER`='1', `PARENT_ID`='67', `PAGE_INFO`='', `DISPLAY_ORDER`='108', `ICON`='', `WEB_INFO`='main.redeemCouponReport', `CREATED_BY`='admin', `CREATED_TIME`='2017-08-15 19:15:00', `UPDATED_BY`='', `UPDATED_TIME`=NULL, `IS_DELETED`='0' WHERE (`ID`='74');
UPDATE `SYSTEM_FUNCTION` SET `ID`='82', `FUNC_CODE`='COLLECT_COUPON_REPORT_VIEW', `FUNC_NAME`='Collect Coupon report view', `FUNC_TYPE`='2', `FUNC_DESC`='Collect Coupon report view', `IS_FOLDER`='0', `PARENT_ID`='73', `PAGE_INFO`='/viewCollectCouponReport,/exportCollectCouponReport', `DISPLAY_ORDER`='116', `ICON`='', `WEB_INFO`='', `CREATED_BY`='admin', `CREATED_TIME`='2017-08-15 19:15:00', `UPDATED_BY`='', `UPDATED_TIME`=NULL, `IS_DELETED`='0' WHERE (`ID`='82');
UPDATE `SYSTEM_FUNCTION` SET `ID`='83', `FUNC_CODE`='REDEEM_COUPON_REPORT_VIEW', `FUNC_NAME`='Redeem Coupon report view', `FUNC_TYPE`='2', `FUNC_DESC`='Redeem Coupon report view', `IS_FOLDER`='0', `PARENT_ID`='74', `PAGE_INFO`='/viewRedeemedtCouponReport,/exportRedeemCouponReport', `DISPLAY_ORDER`='117', `ICON`='', `WEB_INFO`='', `CREATED_BY`='admin', `CREATED_TIME`='2017-08-15 19:15:00', `UPDATED_BY`='', `UPDATED_TIME`=NULL, `IS_DELETED`='0' WHERE (`ID`='83');
UPDATE `SYSTEM_FUNCTION` SET `IS_DELETED`='0' WHERE (`ID`='41');
UPDATE `SYSTEM_FUNCTION` SET `IS_DELETED`='0' WHERE (`ID`='50');
UPDATE `SYSTEM_FUNCTION` SET `IS_DELETED`='0' WHERE (`ID`='51');
UPDATE `SYSTEM_FUNCTION` SET `IS_DELETED`='0' WHERE (`ID`='52');
UPDATE `SYSTEM_FUNCTION` SET `IS_DELETED`='0' WHERE (`ID`='53');

ALTER TABLE `USER` ADD COLUMN `LAST_MOBILE_VERIFY_TIME` datetime DEFAULT NULL;

ALTER TABLE `MERCHANT_CONFIG` MODIFY COLUMN `PUSH_PROJECT_ID`  varchar(50) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL AFTER `IMG_DOMAIN`;
