USE tcc;

-- Update CAMPAIGN_GIFT_EXCHANGE_TYPE
ALTER TABLE `CAMPAIGN_GIFT_EXCHANGE_TYPE` ADD COLUMN `EXTERNAL_RULE_CODE`  varchar(20) NOT NULL AFTER `CAMPAIGN_GIFT_MAP_ID`;

-- Update user stamp history
ALTER TABLE `USER_STAMP_HISTORY` ADD COLUMN `IS_FROM_RESERVATION`  tinyint(1) NULL DEFAULT 0 COMMENT '0 - false 1- true' AFTER `EXTERNAL_STORE_ID`, ADD COLUMN `RESERVATION_PICKUP_DATE`  datetime NULL AFTER `IS_FROM_RESERVATION`;
