-- ----------------------------
-- Table structure for KEEPER_USER
-- ----------------------------
DROP TABLE IF EXISTS `KEEPER_USER`;
CREATE TABLE `KEEPER_USER` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT,
    `MERCHANT_ID` bigint(20) NOT NULL,
    `STORE_ID` bigint(20) NOT NULL,
    `USER_NAME` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
    `PASSWORD` varchar(100) DEFAULT NULL,
    `STAFF_ID` varchar(100) DEFAULT NULL,
    `EMAIL` varchar(50) DEFAULT NULL,
    `MOBILE` varchar(15) DEFAULT NULL,
    `ICON` varchar(100) DEFAULT NULL,
    `SESSION` varchar(100) NOT NULL,
    `STATUS` tinyint(1) NOT NULL COMMENT '状态:0 - InActive  1 - Active',
    
    `CREATED_BY` varchar(100) DEFAULT NULL,
    `CREATED_TIME` datetime DEFAULT NULL,
    `UPDATED_BY` varchar(100) DEFAULT NULL,
    `UPDATED_TIME` datetime DEFAULT NULL,
    `IS_DELETED` tinyint(1) DEFAULT '0',
    PRIMARY KEY (`ID`),
    FOREIGN KEY(MERCHANT_ID) REFERENCES MERCHANT(ID),
    FOREIGN KEY(STORE_ID) REFERENCES STORE(ID),
    UNIQUE KEY(MERCHANT_ID,USER_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for MERCHANT_FUNCTION_FILTER_MAP
-- ----------------------------
DROP TABLE IF EXISTS `MERCHANT_FUNCTION_FILTER_MAP`;
CREATE TABLE `MERCHANT_FUNCTION_FILTER_MAP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MERCHANT_ID` bigint(20) NOT NULL,
  `FUNC_ID` bigint(20) NOT NULL,
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `MERCHANT_ID` (`MERCHANT_ID`) USING BTREE,
  KEY `FUNC_ID` (`FUNC_ID`),
  FOREIGN KEY (`MERCHANT_ID`) REFERENCES `MERCHANT` (`ID`),
  FOREIGN KEY (`FUNC_ID`) REFERENCES `SYSTEM_FUNCTION` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for SYSTEM_FUNCTION_FILTER
-- ----------------------------
DROP TABLE IF EXISTS `SYSTEM_FUNCTION_FILTER`;
CREATE TABLE `SYSTEM_FUNCTION_FILTER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FILTER_CODE` int(11) NOT NULL COMMENT '菜单code',
  `FUNC_ID` bigint(20) NOT NULL COMMENT '菜单 名称',
  `FILTER_NAME` varchar(100) DEFAULT NULL,
  `FILTER_DESC` varchar(200) DEFAULT NULL,
  `CREATED_BY` varchar(100) DEFAULT NULL COMMENT '创建者',
  `CREATED_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(100) DEFAULT NULL COMMENT '修改者',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  `IS_DELETED` tinyint(1) DEFAULT '0' COMMENT '业务删除，是否删除',
  PRIMARY KEY (`ID`),
  KEY `FUNC_ID` (`FUNC_ID`),
  FOREIGN KEY (`FUNC_ID`) REFERENCES `SYSTEM_FUNCTION` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for STAMP_ADJUST_REASON
-- ----------------------------
DROP TABLE IF EXISTS `STAMP_ADJUST_REASON`;
CREATE TABLE `STAMP_ADJUST_REASON` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MERCHANT_ID` bigint(20) NOT NULL,
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `MERCHANT_ID` (`MERCHANT_ID`) USING BTREE,
  FOREIGN KEY (`MERCHANT_ID`) REFERENCES `MERCHANT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for STAMP_ADJUST_REASON_LANG_MAP
-- ----------------------------
DROP TABLE IF EXISTS `STAMP_ADJUST_REASON_LANG_MAP`;
CREATE TABLE `STAMP_ADJUST_REASON_LANG_MAP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `STAMP_ADJUST_REASON_ID` bigint(20) NOT NULL,
  `TITLE` varchar(30),
  `CONTENT` varchar(300) NOT NULL,
  `LANG_CODE` varchar(20) NOT NULL COMMENT '语言编码',
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`STAMP_ADJUST_REASON_ID`) REFERENCES `STAMP_ADJUST_REASON` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
